### PR TITLE
Closes #30 - Create set warp flag

### LINKED ISSUE #30: Check only for real island members when creating warps
**Description**
Players that were cooped or trusted succeeded in creating a warp sign on others people islands. We haven't tested for visitors (With block-placement allowed), but it would be nice if only real team members could be allowed to set a warp sign on their island.

One of the problems this caused was that they were unable to break the warp while the owner or warp-creator was absent.

**Steps to reproduce the behavior:**
1. Go on an island where you are cooped/ trusted
2. Place a warp

**Expected behavior**
Not be able to place a warp

**Server Information:**

 - Database being used: mySQL
 - OS: Linux/ Debian GNU 9
 - Java Version: Java 10
 - BentoBox version: 1.6.0 - SNAPSHOT b1241
 - Addons installed:

```
 BSkyBlock 1.5.0
 AcidIsland 1.5.0
 Welcome-warp sign 1.5.0
 others are not relevant
```

 - Other plugins:
Not relevant

**Additional context**
- Still not sure if visitors with specific flags would be able to place them too

### PR DESCRIPTION
**Pull request by DevSolaris**
Closes #30 
Created a new flag that allows people to choose which ranks can set warps. Also a new config option that allows the server owner to choose if existing warps should be removed when the flag gets updated

### CODE REVIEW

**Review by tastybento — APPROVED** [review]
Nice. Thanks for the PR.

**Comment by BONNe** [comment]
I took the liberty and rename the flag.

SET-WARP did not follow or other flag naming scheme... (not an official requirement).
Also, I add a limitation to not allow VISITORS to be set as a valid group.
And set the default value outside the protection range to false.

**Comment by DevSolaris** [comment]
> I took the liberty and rename the flag.
> 
> SET-WARP did not follow or other flag naming scheme... (not an official requirement). Also, I add a limitation to not allow VISITORS to be set as a valid group. And set the default value outside the protection range to false.

All make sense, Thanks! Was not too sure how to limit it too just "valid" island ranks, and also didn't want to break current behaviour. Thank you!

**Comment by tastybento** [comment]
Next time I will let BONNe comment before I merge in!

**Comment by BONNe** [comment]
No, it is ok.... I did not wanted to comment before you merged in  :D

**Comment by wellnesscookie** [comment]
@DevSolaris thanks, it was a long-waited one for me.

**Pull request merged**
